spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuarioapi
    username: root
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

server:
  error:
    include-message: always

feign:
  viacep:
    url: viacep.com.br/ws/
